version: '3'
services:
  web:
    container_name: pwmgr
    build: ./pwmgr/
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./pwmgr/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pwmgr_admin
      - POSTGRES_PASSWORD=P@ssw0rd123!@#
      - POSTGRES_DB=pwmgr
  nginx:
    build: ./nginx
    ports:
      - 1337:80
      - 1338:443
    depends_on: 
      - web
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  postgres_data: